version: '3'

x-common-variables: &common-variables
  MYSQL_DATABASE: westwing
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  percona_db:
    image: percona
    restart: always
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "13306:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

  webapp1:
    image: node  
    restart: always
    depends_on:
      - percona_db
    ports:
      - "10000:10000"
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: percona_db      
      - PORT=10000
      - SERVER_ID=1

  webapp2:
    image: node  
    restart: always
    depends_on:
      - percona_db
    ports:
      - "10001:10001"
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: percona_db      
      - PORT=10001
      - SERVER_ID=2
      
  nginx:
    depends_on:
      - webapp1
      - webapp2
    restart: always
    ports:
      - "18080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, "-g", "daemon off;"]